### ISSUE TITLE
Crash on some devices while initialising Rive

### ISSUE THREAD

**Issue by kancic** [rive-app/rive-android#283]
### Description
I keep seeing this crash in Firebase on some devices, and I cannot reproduce it. It happens while initialising Rive in the Application's onCreate:

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libndk_translation_proxy_libGLESv3.so" not found
       at java.lang.Runtime.load(Runtime.java:332)
       at java.lang.System.load(System.java:1069)
       at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:31)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:204)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
       at app.rive.runtime.kotlin.core.Rive.init(Rive.kt:30)
```

### Device & Versions
- Devices: Nexus 5X, Oneplus One
- SDK Level: Api level 23

**Comment by PhilippNowak96** [comment]
We are also seeing this on a Nexus 5X in Crashlytics

**Comment by chip2n** [comment]
We are also seeing this, Nexus 5X

**Comment by umberto-sonnino** [comment]
This might be related to our library using GLES3. 
Do you know if the devices you're seeing this on are restricted to GLES2?

**Comment by kancic** [comment]
They should support GLES3

**Comment by PhilippNowak96** [comment]
Looks like it's mainly happening on devices Google uses for testing when you upload your app to the Playstore. We just uploaded a new release with partial rollout and the crash timestamp does not match to a real user already having the app, although we don't see anything in the prelaunch reports or something like that.
