### ISSUE TITLE
libjnirivebridge.so not found in android 8 os(Riv V-4.2.1)

### ISSUE THREAD

**Issue by keyurterran** [rive-app/rive-android#284]
We found below issues while using riv sdk version 4.2.1

Caused by androidx.startup.StartupException: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libjnirivebridge.so'. Looked for: [x86], but only found: [].
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:138)
       at androidx.startup.AppInitializer.initializeComponent(AppInitializer.java:117)
       at com.acecredit.android.ui.SignupActivity.onCreate(SignupActivity.kt:35)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
       
 Device details
Brand:LGE
Model:Nexus 5X
Orientation: Portrait
RAM free: 1.36 GB
Disk free: 413.6 MB
Operating system
Version:Android 8.1.0
Orientation: Portrait
Rooted:No

**Comment by PhilippNowak96** [comment]
I'd like to add a similar stacktrace for another `.so` related to Rive:

```
Caused by java.lang.UnsatisfiedLinkError: dlopen failed: library "libndk_translation_proxy_libGLESv3.so" not found
       at java.lang.Runtime.load(Runtime.java:332)
       at java.lang.System.load(System.java:1069)
       at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:31)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:204)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
       at app.rive.runtime.kotlin.core.Rive.init(Rive.kt:30)
       at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:33)
       at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:31)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:138)
       at androidx.startup.AppInitializer.initializeComponent(AppInitializer.java:117)
```

Happening on an Android 6 device according to crashlytics with Rive Android version 4.2.2

**Comment by umberto-sonnino** [comment]
Hi @keyurterran, could you provide a few more details about the setup and a repro for this issue? 
More specifically, what's the setup for adding the library? Are you seeing this locally on your own device?

**Comment by ryan-cha** [comment]
Having the same issue, too. 

### Error Log
```sh
10:50:16.385 AndroidRuntime  E  FATAL EXCEPTION: main
            Process: app.rive.runtime.example, PID: 23025
            java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: 
                androidx.startup.StartupException: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libjnirivebridge.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
            	at android.app.ActivityThread.installProvider(ActivityThread.java:8313)
            	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7810)
            	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7564)
            	at android.app.ActivityThread.access$1700(ActivityThread.java:315)
            	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286)
            	at android.os.Handler.dispatchMessage(Handler.java:106)
            	at android.os.Looper.loopOnce(Looper.java:226)
            	at android.os.Looper.loop(Looper.java:313)
            	at android.app.ActivityThread.main(ActivityThread.java:8751)
            	at java.lang.reflect.Method.invoke(Native Method)
            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
            Caused by: androidx.startup.StartupException: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libjnirivebridge.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
            	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
            	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
            	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
            	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
            	at android.content.ContentProvider.attachInfo(ContentProvider.java:2516)
            	at android.content.ContentProvider.attachInfo(ContentProvider.java:2486)
            	at android.app.ActivityThread.installProvider(ActivityThread.java:8308)
            	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7810) 
            	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7564) 
            	at android.app.ActivityThread.access$1700(ActivityThread.java:315) 
            	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286) 
            	at android.os.Handler.dispatchMessage(Handler.java:106) 
            	at android.os.Looper.loopOnce(Looper.java:226) 
            	at android.os.Looper.loop(Looper.java:313) 
            	at android.app.ActivityThread.main(ActivityThread.java:8751) 
            	at java.lang.reflect.Method.invoke(Native Method) 
            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
            Caused by: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libjnirivebridge.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
            	at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:175)
            	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
            	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
            	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
            	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
            	at app.rive.runtime.kotlin.core.Rive.init(Rive.kt:30)
            	at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:33)
            	at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:31)
            	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
            	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238) 
            	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206) 
            	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45) 
            	at android.content.ContentProvider.attachInfo(ContentProvider.java:2516) 
            	at android.content.ContentProvider.attachInfo(ContentProvider.java:2486) 
            	at android.app.ActivityThread.installProvider(ActivityThread.java:8308) 
            	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7810) 
            	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7564) 
            	at android.app.ActivityThread.access$1700(ActivityThread.java:315) 
            	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286) 
            	at android.os.Handler.dispatchMessage(Handler.java:106) 
            	at android.os.Looper.loopOnce(Looper.java:226) 
            	at android.os.Looper.loop(Looper.java:313) 
            	at android.app.ActivityThread.main(ActivityThread.java:8751) 
            	at java.lang.reflect.Method.invoke(Native Method) 
            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
```

### How to reproduce. 

1. `git clone https://github.com/rive-app/rive-android.git`
2. `git checkout -b crashtest 1e63dbe`
3. Open the folder in Android Studio
4. Run target `app` or `compatibilitytest`

### Environment 

#### Software
* Android Studio: Flamingo | 2022.2.1
* Kotlin plugin: 222-1.8.0-release-AS3739.54
* Android Gradle Plugin: 7.4.1
* Gradle: 7.5
* Gradle JDK: JetBrains Runtime version 17.0.6

#### Hardware
* Galaxy Tab A7 Lite
  * Model: SM-T225N
  * Android version: v13
* Galaxy Note 10 5G
  * Model: SM-N971N
  * Android version: v12
(The app crashes on both of the devices.)

**Comment by umberto-sonnino** [comment]
Hey @ryan-cha, thanks for providing a repro! 
If you're running it from source you need to also build the libraries and that's why you're getting those missing libs exception - you can find the steps to build those libs [here](https://github.com/rive-app/rive-android/blob/master/CONTRIBUTING.md#building-so-files)

**Comment by ryan-cha** [comment]
@umberto-sonnino Ah! Thank you very much. 
I thought this was a ready-to-run example app. 😅 I'll try again following your instruction!
