### ISSUE TITLE
Cannot locate symbol "stderr" referenced by libjnirivebridge.so

### ISSUE THREAD

**Issue by SoftickSupport** [rive-app/rive-android#293]
**UPD** 15/06/2023

I reproduced the problem on a test project _https://github.com/SoftickSupport/RiveCrash_ .

**Android Studio Emulator API 21**
`implementation 'app.rive:rive-android:4.2.2'` everything is OK,
`implementation 'app.rive:rive-android:4.3.2'` the project crashes,
`implementation 'app.rive:rive-android:5.1.3'` the project crashes. 

**Android Studio Emulator API 22+**
Everything is OK with all versions of the library.

I hope this helps.

----

I added Rive animation to my project some time ago. Until recently, everything was fine.
However, a few days ago, I received a dozen crashes in the Firebase Console.

`
Fatal Exception: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stderr" referenced by "libjnirivebridge.so"...
       at android.app.ActivityThread.installProvider(ActivityThread.java:5694)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:5286)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5226)
       at android.app.ActivityThread.access$1600(ActivityThread.java:181)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6134)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
`

All the crashes are from a single user. 

**Device & Versions**
- Galaxy Tab4 10.1 
- Android v5.0.2
- rive-android library v4.3.2 

Unfortunately, I can't reproduce that problem.
Thanks for any help.

**Comment by berteodosio** [comment]
Are there any updates on this?
I'm also having the same issue, using rive-react-native:
Rive React Native version: 4.1.1

**Comment by mrrobot97** [comment]
I'm facing a similar crash stack trace:


dlopen("/xxx/librive-android.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "stderr" referenced by "librive-android.so"...

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stderr" referenced by "librive-android.so"...
at java.lang.Runtime.load(Runtime.java:331)
at java.lang.System.load(System.java:982)
at a05.d(SourceFile:54)
at a05.c(SourceFile:3)
at app.rive.runtime.kotlin.core.Rive.init(SourceFile:1)
at app.rive.runtime.kotlin.core.Rive.init$default(SourceFile:1)

device: Xiaomi MI2(Android 5.0.2 API21)

**Comment by Athulmohahnan** [comment]
Hi @umberto-sonnino 

Encountering the identical problem with implementation 'app.rive:rive-android:9.0.10' on Android version 5.0.0 (Lollipop). Any progress on resolving this? It seems like this issue has been reported by users for a year now, yet there hasn't been an update.

**Comment by umberto-sonnino** [comment]
> Hi @umberto-sonnino
> 
> Encountering the identical problem with implementation 'app.rive:rive-android:9.0.10' on Android version 5.0.0 (Lollipop). Any progress on resolving this? It seems like this issue has been reported by users for a year now, yet there hasn't been an update.

Hi @Athulmohahnan 
We looked into this last year and we didn't find a fix for it - we're aware that API 21 isn't compatible right now.
We're still looking to sort this out, but the easiest fix at the moment it to target 22 and above.

**Comment by umberto-sonnino** [comment]
Hi @Athulmohahnan and @SoftickSupport 
I went back to this today and the repro provided in the original message (https://github.com/SoftickSupport/RiveCrash), which I can still see crashing on our old version, is building and running fine on our latest `v9.3.2`. 
Can you confirm if that's the case for you too?
