### ISSUE TITLE
crash on 8.2.2

### ISSUE THREAD

**Issue by MKelman** [rive-app/rive-android#303]
### Description

Crash affecting many users.

rive version: 8.2.2

### Provide a Repro

```
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for long app.rive.runtime.kotlin.renderers.Renderer.constructor(boolean, int) (tried Java_app_rive_runtime_kotlin_renderers_Renderer_constructor and Java_app_rive_runtime_kotlin_renderers_Renderer_constructor__ZI)
       at app.rive.runtime.kotlin.renderers.Renderer.constructor(Renderer.kt)
       at app.rive.runtime.kotlin.renderers.Renderer.make(Renderer.kt:62)
       at app.rive.runtime.kotlin.RiveTextureView.onAttachedToWindow(RiveTextureView.kt:69)
       at app.rive.runtime.kotlin.RiveAnimationView.onAttachedToWindow(RiveAnimationView.kt:713)
       at android.view.View.dispatchAttachedToWindow(View.java:20188)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3519)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3519)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3519)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3519)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3519)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3519)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3519)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2137)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1809)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8119)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1043)
       at android.view.Choreographer.doCallbacks(Choreographer.java:866)
       at android.view.Choreographer.doFrame(Choreographer.java:801)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1028)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7615)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

#### Source `.riv`/`.rev` file

[ticket_stars_and_flare.riv.zip](https://github.com/rive-app/rive-android/files/12506122/ticket_stars_and_flare.riv.zip)

### Expected behavior

no crash

### Device & Versions (please complete the following information)

<img width="569" alt="image" src="https://github.com/rive-app/rive-android/assets/10063610/767972b7-42c2-4c7c-83c2-7e80a081d9cd">

**Comment by umberto-sonnino** [comment]
> Hi @umberto-sonnino , no as you can see android 12 is only 47% of the users getting this crash. this is the new breakdown by version <img alt="image" width="635" src="https://user-images.githubusercontent.com/10063610/266056513-f6ac205b-7f4f-4b75-9585-e3a34891be3f.png">

I tried your Rive file and it seems to be working fine in the example app that comes with this repository.
Can you share an example that reproduces the problem you're seeing? A public repo or a gist both work

**Comment by MKelman** [comment]
unfortunately I'm not able to repo it, this is just crashes coming from our companies production. not sure how to further help with this besides the log

**Comment by MKelman** [comment]
@umberto-sonnino I need your help to reproduce this but i can get the test app here to work

<img width="1303" alt="image" src="https://github.com/rive-app/rive-android/assets/10063610/3d62b5bb-4619-4f00-8f03-c6ca97f4b982">

**Comment by MKelman** [comment]
@umberto-sonnino can you try this rive file on your end? this is the new number 1 crash in our app. 
[idle_box_coin_green.riv.zip](https://github.com/rive-app/rive-android/files/12823293/idle_box_coin_green.riv.zip)

**Comment by umberto-sonnino** [comment]
> unfortunately I'm not able to repo it, this is just crashes coming from our companies production. not sure how to further help with this besides the log

Hi @MKelman, we just released a simpler version of our example app which builds right out of the box, you can give it a try from a fresh clone of https://github.com/rive-app/rive-android

> @umberto-sonnino can you try this rive file on your end? this is the new number 1 crash in our app. [idle_box_coin_green.riv.zip](https://github.com/rive-app/rive-android/files/12823293/idle_box_coin_green.riv.zip)

I tried running the default animation in the example app from this repo, but it plays fine. Are you seeing a crash on your end? Can you send the code that's showing the crash?
