### ISSUE TITLE
could not found 'libjnirivebridge.so'. Looked for: [x86], but only found: [].

### ISSUE THREAD

**Issue by devesh053** [rive-app/rive-android#305]
### stacktrace from crashlytics 

Fatal Exception: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'libjnirivebridge.so'. Looked for: [x86, armeabi-v7a, armeabi], but only found: [].
       at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
       at android.app.ActivityThread.access$1100(ActivityThread.java:199)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

### Devices 
Android 9 , Android 8 device with x86 architecture

**Comment by umberto-sonnino** [comment]
Hi @devesh053, can you give us a repro for this issue? 
Also, could you provide more details about your setup? For example, your setup, the rive-android version you're using, your SDK, etc.?
In fact, `libjnirivebridge.so` isn't used anymore in our latest versions, have you tried upgrading?

**Comment by devesh053** [comment]
Hi ,
This issue is happening only on x86 architecture and on crashlytics it was showing Google mainline device.
I was using rive version 5.0.0 in my app.

**Comment by DJPretorius** [comment]
I was having a similar problem and @umberto-sonnino suggested I should upgrade the library to v8.3.0. Thats the second to newest version on [Maven Central](https://mvnrepository.com/artifact/app.rive/rive-android). Now I'm getting an `UnsatisfiedLinkError` when I run my app on Android API 21.
The error reads `java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stderr" referenced by "/data/data/co.example.app/app_lib/librive-android.so"...`

**Comment by devesh053** [comment]
@umberto-sonnino will upgrading to rive  version 6.0.0 resolve the issue ?

**Comment by devesh053** [comment]
> Hi @devesh053, can you give us a repro for this issue? Also, could you provide more details about your setup? For example, your setup, the rive-android version you're using, your SDK, etc.? In fact, `libjnirivebridge.so` isn't used anymore in our latest versions, have you tried upgrading?

Right now , I am using 5.0.0 , will upgrading it to 6.0.0 will resolve the issue . Not sure of taking version 7.0.0 to production

**Comment by umberto-sonnino** [comment]
> @umberto-sonnino will upgrading to rive version 6.0.0 resolve the issue ?

Without a repro, I can't tell for sure. 
Past reports mentioned that this error was coming up [only in the Play Store](https://github.com/rive-app/rive-android/issues/283#issuecomment-1490127290) - are you sure that these are tied to real users?
I'd highly recommend upgrading anyway, we changed the build process significantly in the latest iterations, and that might solve this issue for you.

**Comment by umberto-sonnino** [comment]
> I was having a similar problem and @umberto-sonnino suggested I should upgrade the library to v8.3.0. Thats the second to newest version on [Maven Central](https://mvnrepository.com/artifact/app.rive/rive-android). Now I'm getting an `UnsatisfiedLinkError` when I run my app on Android API 21. The error reads `java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "stderr" referenced by "/data/data/co.example.app/app_lib/librive-android.so"...`

@DJPretorius this is a different bug as reported [here](https://github.com/rive-app/rive-android/issues/293). It's still unresolved and it seems to happen only on v21 devices

**Comment by devesh053** [comment]
> > @umberto-sonnino will upgrading to rive version 6.0.0 resolve the issue ?
> 
> Without a repro, I can't tell for sure. Past reports mentioned that this error was coming up [only in the Play Store](https://github.com/rive-app/rive-android/issues/283#issuecomment-1490127290) - are you sure that these are tied to real users? I'd highly recommend upgrading anyway, we changed the build process significantly in the latest iterations, and that might solve this issue for you.

This bug is not happening to real users , only happening to play store devices with x86 architecture .

**Comment by umberto-sonnino** [comment]
> > > @umberto-sonnino will upgrading to rive version 6.0.0 resolve the issue ?
> > 
> > 
> > Without a repro, I can't tell for sure. Past reports mentioned that this error was coming up [only in the Play Store](https://github.com/rive-app/rive-android/issues/283#issuecomment-1490127290) - are you sure that these are tied to real users? I'd highly recommend upgrading anyway, we changed the build process significantly in the latest iterations, and that might solve this issue for you.
> 
> This bug is not happening to real users , only happening to play store devices with x86 architecture .

If that's the case, I highly recommend upgrading to the latest version and checking if it still applies. The current report is related to an old version of this runtime.

**Comment by ErikUggeldahl** [comment]
Hi all. Closing this issue as stale. It's possible that the crashes are Play Store runners. If this occurs in a modern version of the SDK (v10+) we can consider re-opening.
