### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found

### ISSUE THREAD

**Issue by GOVINDDIXIT** [rive-app/rive-android#315]
### Description

Getting following issue while initialising rive for Vivo and Oneplus devices
```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found: needed by /data/data/com.dreamplug.androidapp/app_lib/librive-android.so in namespace clns-5
       at java.lang.Runtime.load0(Runtime.java:933)
       at java.lang.System.load(System.java:1625)
       at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:31)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:206)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:133)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
       at app.rive.runtime.kotlin.core.Rive.init(Rive.kt:43)
       at app.rive.runtime.kotlin.core.Rive.init$default(Rive.kt:38)
       at com.dreamplug.fabrik.ui.main.MainActivity$onCreate$1.invokeSuspend(MainActivity.kt:246)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:5793)
```

### Provide a Repro

Just initialising the Rive is able to repro the crash

### Device & Versions (please complete the following information)

- Device: 
Brand: Vivo
Model: X90

- SDK Level 
Android 14 (API level 34)

**Comment by umberto-sonnino** [comment]
Hi @GOVINDDIXIT, we also test against a OnePlus 7Pro on our end and everything runs smoothly over here. 
Which OnePlus device are you seeing this on? Are you seeing this by just running the example app in this repo?

**Comment by DJPretorius** [comment]
Hi @umberto-sonnino I am unable to reporduce this crash but I have reports on Crashlytics indicating the same crash as mentioned above.
* Devices:
Samsung Gallaxy J4 Core
Samsung Gallaxy A2 Core

100% of affected devices are running Android 8.

* Rive version: 8.3.0

**Comment by nshurtz** [comment]
Seeing this for 2 users, OnePlus Nord N30 5G and Moto G Play - 2024 both running Android 14. Rive 10.0.5
