### ISSUE TITLE
App crashed at librive-android.so on SDK Android 15 and 16kb page size supported device

### ISSUE THREAD

**Issue by vegeta2102** [rive-app/rive-android#329]
### Description

In order to update Android 15 release next year I'm trying to build app on an emulator with Android 15 with support for 16KB page sizes.
Doc : https://developer.android.com/guide/practices/page-sizes

App crashed at starting point. Here is the log

### Error

```
06-13 16:06:50.664 30939 30939 E AndroidRuntime: FATAL EXCEPTION: main
06-13 16:06:50.664 30939 30939 E AndroidRuntime: Process: jp.eure.android.pairs, PID: 30939
06-13 16:06:50.664 30939 30939 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/data/jp.eure.android.pairs/app_lib/librive-android.so" (new hash type from the future?)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:8266)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7776)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7465)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2399)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8674)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: Caused by: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/data/jp.eure.android.pairs/app_lib/librive-android.so" (new hash type from the future?)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2644)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2613)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:8261)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	... 11 more
06-13 16:06:50.664 30939 30939 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/data/jp.eure.android.pairs/app_lib/librive-android.so" (new hash type from the future?)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at java.lang.Runtime.load0(Runtime.java:933)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at java.lang.System.load(System.java:1729)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:31)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:206)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at app.rive.runtime.kotlin.core.Rive.init(Rive.kt:42)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at app.rive.runtime.kotlin.core.Rive.init$default(Rive.kt:37)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:34)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:32)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
06-13 16:06:50.664 30939 30939 E AndroidRuntime: 	... 17 more
06-13 16:06:55.641 31011 31011 E AndroidRuntime: FATAL EXCEPTION: main
06-13 16:06:55.641 31011 31011 E AndroidRuntime: Process: jp.eure.android.pairs, PID: 31011
06-13 16:06:55.641 31011 31011 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/data/jp.eure.android.pairs/app_lib/librive-android.so" (new hash type from the future?)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:8266)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7776)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7465)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2399)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8674)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: Caused by: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/data/jp.eure.android.pairs/app_lib/librive-android.so" (new hash type from the future?)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2644)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2613)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:8261)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	... 11 more
06-13 16:06:55.641 31011 31011 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/data/jp.eure.android.pairs/app_lib/librive-android.so" (new hash type from the future?)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at java.lang.Runtime.load0(Runtime.java:933)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at java.lang.System.load(System.java:1729)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:31)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:206)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at app.rive.runtime.kotlin.core.Rive.init(Rive.kt:42)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at app.rive.runtime.kotlin.core.Rive.init$default(Rive.kt:37)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:34)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:32)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
06-13 16:06:55.641 31011 31011 E AndroidRuntime: 	... 17 more

```

### Device & Versions (please complete the following information)

- Device: Android Emulator VanillaIceCream Preview (16k Page Size ARM 64 v8a)
- SDK Level : Android SDK API Level 35 VanillaIceCream Preview

**Comment by blowonthepi** [comment]
I am also finding this, I've tested on Android 14 & 15.

```csharp
 java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/data/[application.id]/app_lib/librive-android.so" (new hash type from the future?)
   at android.app.ActivityThread.installProvider(ActivityThread.java:8297 undefined)
   at android.app.ActivityThread.installContentProviders(ActivityThread.java:7807 undefined)
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7488 undefined)
   at android.app.ActivityThread.-$Nest$mhandleBindApplication(Unknown Source:0)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2416 undefined)
   at android.os.Handler.dispatchMessage(Handler.java:107 undefined)
   at android.os.Looper.loopOnce(Looper.java:232 undefined)
   at android.os.Looper.loop(Looper.java:317 undefined)
   at android.app.ActivityThread.main(ActivityThread.java:8705 undefined)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580 undefined)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886 undefined)
Caused by: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/data/[application.id]/app_lib/librive-android.so" (new hash type from the future?)
   at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187 undefined)
   at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238 undefined)
   at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206 undefined)
   at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45 undefined)
   at android.content.ContentProvider.attachInfo(ContentProvider.java:2644 undefined)
   at android.content.ContentProvider.attachInfo(ContentProvider.java:2613 undefined)
   at android.app.ActivityThread.installProvider(ActivityThread.java:8292 undefined)
                                                                                                    	... 11 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/data/[application.id]/app_lib/librive-android.so" (new hash type from the future?)
   at java.lang.Runtime.load0(Runtime.java:933 undefined)
   at java.lang.System.load(System.java:1729 undefined)
   at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:31 undefined)
   at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:206 undefined)
   at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136 undefined)
   at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70 undefined)
   at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51 undefined)
   at app.rive.runtime.kotlin.core.Rive.init(Rive.kt:42 undefined)
   at app.rive.runtime.kotlin.core.Rive.init$default(Rive.kt:37 undefined)
   at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:34 undefined)
   at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:32 undefined)
   at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180 undefined)
                                                                                                    	... 17 more

```

**Comment by georgmay** [comment]
Same issue, just occurred for me

**Comment by ErikUggeldahl** [comment]
Hi all. Just wanted to comment that we are looking into this actively. It shouldn't be terribly long before we have a fix in place.

**Comment by 1gravity** [comment]
Has there been progress on this? It prevents us from targeting Android 15. Thanks

**Comment by vegeta2102** [comment]
Thank you very much !
