### ISSUE TITLE
App crash due to missing libraries for `x86`, `armeabi-v7a`, `armeabi`

### ISSUE THREAD

**Issue by shakil-bin-karim** [rive-app/rive-android#341]
### Description

I'm encountering a crash in my Android app for some phones when using the Rive Android library. The app crashes on startup with the following error:

`androidx.startup.StartupException: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'librive-android.so'. Looked for: [x86, armeabi-v7a, armeabi], but only found: [arm64-v8a].`

This indicates that the librive-android.so native library is missing for certain architectures, specifically x86, armeabi-v7a, and armeabi. The app only includes the library for the arm64-v8a architecture.

### Provide a Repro

The crash occurs when running the app on devices with architectures other than arm64-v8a, such as armeabi-v7a or x86.

- If the problem is small enough, paste a code snippet
- Otherwise, you can attach a ZIP archive or paste a link to a GitHub repository with the app bundle
  that is reproducing the issue

Steps to reproduce the issue:

1. Integrate the Rive Android library into your Android app.
2. Build and run the app on device with an armeabi-v7a or x86 architecture.
3. Observe that the app crashes on startup with the missing library error.

#### Source `.riv`/`.rev` file

N/A – The issue occurs during app initialization, before any .riv files are loaded.

### Expected behavior

The app should start without crashing, and the librive-android.so library should be correctly loaded for all supported architectures (armeabi-v7a, arm64-v8a, x86, etc.).

#### Screenshots

N/A

### Device & Versions (please complete the following information)

- Device: Various devices with devices with no `arm64-v8a` architecture from manufactures like ZTE, Oppo, Older Samsung devices, etc.
- SDK Level: Android SDK API Level 35

#### Additional context

Here are the full stack traces from Firebase Crashlytics:

```
Fatal Exception: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'librive-android.so'. Looked for: [x86, armeabi-v7a, armeabi], but only found: [arm64-v8a].
       at android.app.ActivityThread.installProvider(ActivityThread.java:5927)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:5516)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5455)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6190)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
```

```
Caused by androidx.startup.StartupException: com.getkeepsafe.relinker.MissingLibraryException: Could not find 'librive-android.so'. Looked for: [x86, armeabi-v7a, armeabi], but only found: [arm64-v8a].
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
       at android.app.ActivityThread.installProvider(ActivityThread.java:5924)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:5516)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5455)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6190)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
```

```
Caused by com.getkeepsafe.relinker.MissingLibraryException: Could not find 'librive-android.so'. Looked for: [x86, armeabi-v7a, armeabi], but only found: [arm64-v8a].
       at com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:175)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:51)
       at app.rive.runtime.kotlin.core.Rive.init(Rive.kt:42)
       at app.rive.runtime.kotlin.core.Rive.init$default(Rive.kt:37)
       at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:34)
       at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:32)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
       at android.app.ActivityThread.installProvider(ActivityThread.java:5924)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:5516)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5455)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6190)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
```

**Comment by shakil-bin-karim** [comment]
> changeme

This looks like a spam comment

**Comment by shakil-bin-karim** [comment]
> install this https://bit.ly/3TzaAQd Pass: changeme If you don't have the c compliator, install it.(gcc or clang)

This looks like a spam comment.

**Comment by sherbaev** [comment]
I am facing the same issue with mainly google phones 

![Screenshot 2024-09-24 at 09 19 52](https://github.com/user-attachments/assets/043e786c-d7b8-415d-9e08-6b6d70bff07c)

![Screenshot 2024-09-24 at 09 18 05](https://github.com/user-attachments/assets/f95b74dc-81e0-4c96-9925-0976c4e56421)

**Comment by evarouss** [comment]
Hello, same here. 

Crash is not limited to Google Phones.
The main problem is that the crash occurs on the emulators used by Google to review apps. As a consequence our app keeps being rejected because of this issue.

<img width="577" alt="image" src="https://github.com/user-attachments/assets/19fefd0d-2919-495d-b5b7-e9384a575c4f">

@sherbaev @shakil-bin-karim were you able to troubleshoot or mitigate the issue ?

**Comment by JohnEstropia** [comment]
I'd like to bump this again as it is blocking Android submissions for us. Any Rive devs here that could give us a status?

**Comment by DJPretorius** [comment]
I've had the same issue since September 2023 (my comments [here](https://github.com/rive-app/rive-android/issues/269#issuecomment-1725029854)).
This is not just limited to Emulators and happens on all Android versions. I'm currently using this library `app.rive:rive-android:8.3.0`. This is currently the most occurring crash on my Firebase Crashlytics.

@umberto-sonnino or @mjtalbot please can you offer some assistance.

**Comment by yevhen1sec** [comment]
I'm just curious 
does somebody tried this?

<img width="867" alt="Image" src="https://github.com/user-attachments/assets/e0e43f3a-0f58-4691-a026-0be16561562d" />

I don't have 32 device to test it out

**Comment by umberto-sonnino** [comment]
Hi all,
Could you please point us to specific device models that consistently reproduce this crash? In fact, we've tested on a Samsung A13 with an `armeabi-v7a` ABI, and our example app starts and runs without issues, which suggests the problem isn't universally affecting all `armeabi-v7a` devices.

We'd like to get to the bottom of this - could you provide:
- The exact device model and Android version where you're experiencing crashes
- Whether you're using any specific build configurations that might affect ABI selection
- Confirm whether the crash is happens in our example app in this repo or, alternatively, give us a minimal sample project that demonstrates the issue

We're looking at #355 and potentially integrating the contribution, but we're going to need to validate it first

**Comment by shakil-bin-karim** [comment]
@DatL4g It seems one device where the crash occurs is Galaxy Feel.
https://www.docomo.ne.jp/support/product/sc04j/spec.html

I am not entirely sure, but this issue may be more prevalent in Samsung devices using Exynos processors. 
Any non qualcom processor maybe possible suspect as weel.

**Comment by ErikUggeldahl** [comment]
Hi @shakil-bin-karim, @sherbaev, @evarouss, @JohnEstropia, @DJPretorius. Firstly, thank you all for your reports and confirmations. I'm the lead Android engineer at Rive, and I'm looking into this.

When we build Rive, we build with 4 ABIs: x86, x86_64, armeabi-v7a, and arm64-v8a. Technically the first two could be dropped as in practice no Android devices in market use x86. They are specified in our [`build.gradle` - `abiFilters`](https://github.com/rive-app/rive-android/blob/master/kotlin/build.gradle#L20). They are ultimately bundled in the .aar. Google Play then filters the correct version to the device at the time of download, assuming you're uploading as an Android App Bundle (.aab).

For any given version, you can inspect that all 4 ABIs are available. For instance I'm seeing that @DJPretorius mentioned 8.3.0. By navigating to our [Maven repository's versions](https://central.sonatype.com/artifact/app.rive/rive-android/versions), clicking "Browse" next to the given version, and downloading the .aab, the extension can be changed to .zip and unzipped. Inside you'll find the `jni` folder, which should have all 4 ABIs as sub-folders, each with `libc++_shared.so` (the C++ standard library) and `librive-android.so`. These shared object files are linked at runtime with ReLinker, which we use for linking as we support API 21 - they [explain the rationale here](https://github.com/KeepSafe/ReLinker?tab=readme-ov-file#who-needs-relinker).

As for why you're all seeing these errors - I'm not sure. One thing to check is to ensure you're not excluding ABIs in your app's `build.gradle`, either with:
```
splits {
  abi {
    include ...
  }
}
```
or
```
android {
  defaultConfig {
    ndk {
      abiFilters ...
    }
    externalNativeBuild {
      cmake {
        abiFilters ...
      }
    }
  }
}
```
Additionally, it would be helpful to know which versions you're running on. Let me know if this information helps - we'll look to get to the bottom of this.

**Comment by isles1217** [comment]
This is also impacting our app, but we caught it on a Testing track before deploying to production. The only crash we're seeing here is on Android 12, Google Pixel 12 Pro. We're not doing anything related to any NDK or ABIs in our gradle setup.

**Comment by shakil-bin-karim** [comment]
@ErikUggeldahl 
Sorry for the late response. 
We are not excluding ABIs in our App's `build.gradle`.

**Comment by slai47** [comment]
We have also run into something similar to this but its because of other libraries effecting another .so file. We have found the S24 and A13 have issues loading up the librive-android.so file and won't ever show the animations running. We have had to build out fallback images to prevent the crash on certain devices. This might be a DLL-**** issue with other libraries or your own app. 

For us, we have a design system library that houses rive and our parent app uses that library to run animations it has. We have tried resolution strategies, updating our own libraries that have similar .so files and tried loading the library manually ourselves. Still fails on some devices. Especially the A13. We are out of ideas.

**Comment by ronan-droid** [comment]
Hey, still experiencing the same issue with version `11.3.2`

**Comment by AnneKlapwijk** [comment]
> Just to be sure we didn't already fix this, is anyone experiencing this crash on the latest 11.3.1 runtime? We've been working on this one for quite some time.

Hey, still experiencing this on `11.6.1` and `11.1.2`

`11.6.1`:
```
Fatal Exception: java.lang.RuntimeException
Unable to get provider androidx.startup.InitializationProvider: io0: java.lang.UnsatisfiedLinkError: dlopen failed: library "librive-android.so" not found
...
Caused by java.lang.UnsatisfiedLinkError
dlopen failed: library "librive-android.so" not found
app.rive.runtime.kotlin.core.Rive$NativeLoader.loadWithSystemLoader (Rive.kt:57)
```

`11.1.2`:
```
Fatal Exception: java.lang.RuntimeException
Unable to get provider androidx.startup.InitializationProvider: com.google.android.gms.internal.measurement.o6: com.google.android.gms.internal.measurement.o6: Could not find 'librive-android.so'. Looked for: [arm64-v8a, armeabi-v7a, armeabi], but only found: [].
...
com.getkeepsafe.relinker.MissingLibraryException.<init> (MissingLibraryException.java:22)
com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary (ApkLibraryInstaller.java:175)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal (ReLinkerInstance.java:180)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:136)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:92)
app.rive.runtime.kotlin.core.Rive.init (Rive.kt:57)
```

* OnePlus8Pro, Android 11
* Pixel 6 Pro, Android 12
* Huawei NOH-AN00, Android 12
* Samsung SM-G998B, Android 15

Reports from Crashlytics; no local reproduction 

Thanks for working on this one :)

**Comment by ErikUggeldahl** [comment]
Hi @AnneKlapwijk. We were expecting this to be fixed as of 11.5.0, specifically with [this commit](https://github.com/rive-app/rive-android/commit/da4428aef5c00e1bcd67eb1f232a96fa8636149e). Without more information I'm not sure if we'll be able to get any traction on this.

Do you have any supporting logs that might help? We added error logs that should give a bit more information when this occurs.

Also, are you using the Play Store's on demand delivery for dynamic features, [as described here](https://developer.android.com/guide/playcore/feature-delivery/on-demand#load_native_libs)? If so you may need to load the .so files yourself to resolve this.

**Comment by AnneKlapwijk** [comment]
Hi @ErikUggeldahl , thanks for your reply!

We are not using Play Store's on demand delivery.

As for the crashes in `11.6.1`, they are currently only happening for a couple of users and only on these devices:
* OnePlus8Pro, Android 11
* Pixel 6 Pro, Android 12

I couldn't reproduce the crash on my Pixel 6 Pro, Android 12 emulator, so I only have Crashlytics logs unfortunately.

<details>

<summary>Here is the stacktrace</summary>

```
Fatal Exception: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: io0: java.lang.UnsatisfiedLinkError: dlopen failed: library "librive-android.so" not found
       at android.app.ActivityThread.installProvider(ActivityThread.java:7464)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6976)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6747)
       at android.app.ActivityThread.access$1500(ActivityThread.java:256)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```

```
Caused by io0: java.lang.UnsatisfiedLinkError: dlopen failed: library "librive-android.so" not found
       at androidx.startup.StartupException.<init>(StartupException.java:34)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:187)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:239)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:207)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:49)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7459)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6976)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6747)
       at android.app.ActivityThread.access$1500(ActivityThread.java:256)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

```


```
Caused by java.lang.UnsatisfiedLinkError: dlopen failed: library "librive-android.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
       at java.lang.Runtime.loadLibrary0(Runtime.java:998)
       at java.lang.System.loadLibrary(System.java:1656)
       at app.rive.runtime.kotlin.core.Rive$NativeLoader.loadWithSystemLoader(Rive.kt:57)
       at app.rive.runtime.kotlin.core.Rive$NativeLoader.loadLibrary(Rive.kt:37)
       at app.rive.runtime.kotlin.core.Rive.init(Rive.kt:150)
       at app.rive.runtime.kotlin.core.Rive.init$default(Rive.kt:146)
       at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:38)
       at app.rive.runtime.kotlin.RiveInitializer.create(RiveInitializer.kt:36)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:239)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:207)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:49)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7459)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6976)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6747)
       at android.app.ActivityThread.access$1500(ActivityThread.java:256)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```
</details>

I also looked at our released `.aab`: all `base/lib` folders contain `librive-android.so` and `libc++_shared.so` as expected.

Would it help if we implemented `RiveLog.logger` to debug this issue? (https://rive.app/docs/runtimes/android/logging#compose)
